# # PostgreSQL のインストールとデータ投入
---
- name: roles/postgresql/tasks/main.yml
  set_fact: pg_need_install=true
  tags: init
- name: PGDG リポジトリ存在チェック
  stat: path=/etc/yum.repos.d/{{PG_REPO_FILE}}
  register: pgdg
- include: package.yml
  when: 
    - pg_need_install == true
    - pgdg.stat.exists == false
  ignore_errors: yes
- include: init.yml
  when:
    - pg_need_install == true
  ignore_errors: yes
  tags: init
