---
- name: roles/postgresql/tasks/package.yml
  command: echo
- name: Remove old postgresql data
  file: path=/var/lib/pgsql/data state=absent
  become: yes
- name: Install PGDG repository
  yum: name={{ PG_REPO_URI }} state=present
  become: yes
- name: Install postgresql packages
  yum: name={{item}} state=present
  with_items:
    - postgresql96-server
    - postgresql96-devel
    - "{{ PHP_PKG_PREFIX }}-pgsql"
    - python-psycopg2
  become: yes
- name: Add /usr/pgsql-9.6/bin to $PATH
  template:
    src: pgsql.sh
    dest: /etc/profile.d
  become: yes
