---
- name: roles/nginx/tasks/main.yml
  command: echo
- name: Install nginx1w from webtatic repository for CentOS 7.x
  yum: name={{ item }} state=present
  with_items:
    - nginx1w
  become: yes
  when: ansible_distribution_major_version == '7'
- name: Install nginx from standard repository for CentOS 6.x
  yum: name={{ item }} state=present
  with_items:
    - nginx
  become: yes
  when: ansible_distribution_major_version == '6'
- name: nginx - Change log setting
  lineinfile:
    dest:   /etc/nginx/nginx.conf
    regexp: "^error_log /var/log/nginx/error.log"
    line:   "error_log /var/log/nginx/error.log warn;"
  become: yes
- name: nginx - Add common settings
  copy:
    dest: /etc/nginx/conf.d/
    src:  http_common.conf
  become: yes
- name: Enable nginx
  command: echo
  notify: restart nginx
