---
- name: roles/php-fpm/tasks/main.yml
  command: echo
- name: Install package from additional repository
  yum:
    name: "{{ item }}"
    state:  present
  with_items:
    - "{{ PHP_PKG_PREFIX }}-fpm"
  become: yes

- include: "{{ PHP_REPO }}.yml"

- name: php-fpm.conf - Use epoll instead of poll
  lineinfile:
    dest: "{{ PHP_INI_DIR }}/php-fpm.conf"
    regexp:  ^;events.mechanism = epoll
    line: events.mechanism = epoll
  become: yes

- name: php-fpm.d/www.conf - change user
  lineinfile:
    dest: "{{ PHP_INI_DIR }}/php-fpm.d/www.conf"
    regexp:  ^user = apache
    line: user = {{ WEBSERVER_USER }}
  become: yes

- name: php-fpm.d/www.conf - change group
  lineinfile:
    dest: "{{ PHP_INI_DIR }}/php-fpm.d/www.conf"
    regexp:  ^group = apache
    line: group = {{ WEBSERVER_GROUP }}
  become: yes

- name: php-fpm.d/www.conf - change listen method
  lineinfile:
    dest: "{{ PHP_INI_DIR }}/php-fpm.d/www.conf"
    regexp:  ^listen = 127.0.0.1:9000
    line: listen = /var/run/php-fpm/php-fpm.sock
  become: yes

- name: php-fpm.d/www.conf - change listen owner
  lineinfile:
    dest: "{{ PHP_INI_DIR }}/php-fpm.d/www.conf"
    regexp:  ^;listen.owner = nobody
    line: listen.owner = nginx
  become: yes

- name: php-fpm.d/www.conf - change listen group
  lineinfile:
    dest: "{{ PHP_INI_DIR }}/php-fpm.d/www.conf"
    regexp:  ^;listen.group = nobody
    line: listen.group = nginx
  become: yes

- name: php-fpm.d/www.conf - add setting for use in Japan
  blockinfile:
    dest: "{{ PHP_INI_DIR }}/php-fpm.d/www.conf"
    insertafter:  '^;php_value[opcache.file_cache]'
    block: |
      ; Default values for use in Japan.
      php_value[date.timezone] = {{ TIME_ZONE }}
      php_value[mbstring.language] = Japanese
  become: yes
  notify: restart {{ PHP_FPM_SERVICE }}
