---
- name: roles/php-fpm/tasks/main.yml
  command: echo
- name: Install package from additional repository
  yum:
    name: "{{ item }}"
    state:  present
  with_items:
    - "{{ PHP_PKG_PREFIX }}-fpm"
  become: yes

- include: "{{ PHP_REPO }}.yml"

- name: php-fpm.conf - Use epoll instead of poll
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php-fpm.conf"
    regexp:       ^events.mechanism = epoll
    line:         events.mechanism = epoll
    insertafter:  ^;events.mechanism = epoll
  become: yes

- name: apply changes
  notify: restart {{ PHP_FPM_SERVICE }}
  become: yes
