---
- name: roles/laravel/tasks/aws.yml
  command: echo

- name: 1.Check for aws-sdk-php-laravel
  stat: path={{ LARAVEL_HOME }}/vendor/aws/aws-sdk-php-laravel
  register: aws

- name: 2.Install aws-sdk-php-laravel
  composer:
    command: require
    arguments: "aws/aws-sdk-php-laravel:~3.0"
    working_dir: "{{ LARAVEL_HOME }}"
  when: aws.stat.exists == false
  environment:
    PATH: "/usr/bin:{{ PHP_BIN_DIR }}:{{ COMPOSER_GLOBAL_BIN }}"

- name: 3.Enable AwsServiceProvider
  lineinfile:
    dest: "{{ LARAVEL_HOME }}/config/app.php"
    regexp: "^ +Aws"
    line:   "        Aws\\Laravel\\AwsServiceProvider::class,"
    insertafter: 'RouteServiceProvider'

- name: 4.Insert AwsFacade
  lineinfile:
    dest: "{{ LARAVEL_HOME }}/config/app.php"
    regexp: "^ +'AWS'"
    line:   "        'AWS' => Aws\\Laravel\\AwsFacade::class,"
    insertafter: "'App'"
