---
- name: roles/laravel/tasks/core.yml
  command: echo

- name: core-01.Check for existence of the laravel installer
  stat: path={{ COMPOSER_GLOBAL_BIN }}/laravel
  register: laravel_installer

- name: core-02.Install laravel installer
  composer:
    command: require
    arguments: "laravel/installer"
    working_dir: "{{ COMPOSER_HOME }}"
  when: 
    - laravel_installer.stat.exists is defined
    - laravel_installer.stat.exists == false
  become: yes
  environment:
    PATH: "/usr/bin:{{ PHP_BIN_DIR }}:{{ COMPOSER_GLOBAL_BIN }}"

- name: core-03.Put laravel.conf for nginx
  template:
    src:  laravel.conf
    dest: /etc/nginx/conf.d/laravel.conf
    force: no
  become: yes
  notify: reload nginx

- name: core-04.Prepar directory for LARAVEL_BASE
  file: 
    path:     "{{ LARAVEL_BASE }}"
    state:    directory
    owner:    "{{ ansible_user_id }}"
  become: yes

- name: core-05.Deploy laravel installation
  command: "{{ LARAVEL_BIN }} new laravel"
  args:
    creates: "{{ LARAVEL_BASE }}/laravel"
    chdir: "{{ LARAVEL_BASE }}"
  environment:
    PATH: "/usr/bin:{{ PHP_BIN_DIR }}:{{ COMPOSER_GLOBAL_BIN }}"

- name: core-06.Change owner under laravel
  file: 
    path:     "{{ LARAVEL_HOME }}" 
    state:    directory
    owner:    "{{ ansible_user_id }}"
    recurse:  yes
  become: yes

- name: core-07.Open permissions of storage/*
  file: 
    path:     "{{ LARAVEL_HOME }}/storage" 
    state:    directory
    mode:     "a+w" 
    recurse:  yes
  become: yes

- name: core-08.Open permissions of bootstrap/cache
  file: 
    path:     "{{ LARAVEL_HOME }}/bootstrap/cache"
    state:    directory
    mode:     "a+w" 
    recurse:  yes
  become: yes
  notify: start {{ PHP_FPM }}
