---
- name: roles/laravel/tasks/db-pgsql.yml
  command: echo

- name: Create User
  postgresql_user:
    name: "{{ LARAVEL_DB_USERNAME }}"
    role_attr_flags: SUPERUSER

- name: Create Database
  postgresql_db:
    name: "{{ LARAVEL_DB_DATABASE }}"
  ignore_errors: yes
