---
- name: roles/laravel/tasks/japan.yml
  command: echo

- name: 1.Change LANG env
  lineinfile:
    dest:   "/home/{{ ansible_user_id }}/.bashrc"
    regexp: "^export LANG="
    line:   "export LANG=ja_JP.UTF-8"
  when:     PHP_JAPANIZE == true
