---
- name: roles/laravel/tasks/main.yml
  command: echo
- include: core.yml
  tags: laravel
- include: env.yml
- include: localize.yml
- include: db-pgsql.yml
  when: LARAVEL_DB_CONNECTION == "pgsql"
- include: db-mysql.yml
  when: LARAVEL_DB_CONNECTION == "mysql"
- include: db-sqlite.yml
  when: LARAVEL_DB_CONNECTION == "sqlite"
- include: whoops.yml
# - include: debugbar.yml
- include: aws.yml
- include: vendor.yml
