---
- name: roles/laravel/tasks/main.yml
  command: echo
- include: core.yml
- include: env.yml
- include: localize.yml
- include: db.yml
- include: whoops.yml
# - include: debugbar.yml
- include: aws.yml
- include: vendor.yml
