---
- name: roles/ci3/tasks/postgre.yml
  command: echo

- name: Create Database User
  postgresql_user:
    name: "{{ CI3_DB_USERNAME }}"
    role_attr_flags: SUPERUSER

- name: Create Databse
  postgresql_db:
    name: "{{ CI3_DB_DATABASE }}"
  ignore_errors: yes

- name: Customise database.php(hostname)
  lineinfile:
    path: "{{ CI3_APP_DIR }}/config/database.php"
    regexp: "^\\t'hostname'"
    line: "\t'hostname' => '{{ CI3_DB_HOST }}',"
    backrefs: yes

- name: Customise database.php(username)
  lineinfile:
    path: "{{ CI3_APP_DIR }}/config/database.php"
    regexp: "^\\t'username'"
    line: "\t'username' => '{{ CI3_DB_USERNAME }}',"
    backrefs: yes

- name: Customise database.php(password)
  lineinfile:
    path: "{{ CI3_APP_DIR }}/config/database.php"
    regexp: "^\\t'password'"
    line: "\t'password' => '{{ CI3_DB_PASSWORD }}',"
    backrefs: yes

- name: Customise database.php(database)
  lineinfile:
    path: "{{ CI3_APP_DIR }}/config/database.php"
    regexp: "^\\t'database'"
    line: "\t'database' => '{{ CI3_DB_DATABASE }}',"
    backrefs: yes

- name: Customise database.php(dbdriver)
  lineinfile:
    path: "{{ CI3_APP_DIR }}/config/database.php"
    regexp: "^\\t'dbdriver'"
    line: "\t'dbdriver' => '{{ CI3_DB_DRIVER }}',"
    backrefs: yes

