---
- name: roles/ldap/tasks/install.yml
  command: echo
- name: Install LDAP support packages
  yum: 
    name: "{{ item }}"
  with_items:
    - openldap-servers
    - openldap-clients
  become: yes
- name: Set DB_CONFIG
  copy:
    src: /usr/share/openldap-servers/DB_CONFIG.example
    dest: /var/lib/ldap/DB_CONFIG
    remote_src: true
  become: yes
  become_user: ldap
  notify: start slapd
