# OpenJDK
---
- name: roles/openjdk/tasks/main.yml
  command: echo

- name: Install packages required for OpenJDK
  yum: name={{ item }} state=present
  with_items:
    - java-1.8.0-openjdk
  become: yes
