---
- name: roles/wordpress/tasks/core.yml
  set_fact:
    WP_CLI: /usr/local/bin/wp

- name: Get wp-cli if not exists
  get_url:
    url: "{{ WP_CLI_ARCHIVE }"
    dest: "{{ WP_CLI }}"
    mode: 0755
  become: yes

- name: Get WP_ARCHIVE if not already downloaded
  get_url:
    url: "{{ WP_ARCHIVE_URL }}"
    dest: /tmp/{{ WP_ARCHIVE }}

- name: Extract core archive
  unarchive:
    src: /tmp/{{ WP_ARCHIVE }}
    dest: "{{ WWW_BASE }}"
    remote_src: yes
  become: yes

- name: Configure wp instance
  shell: "{{ WP_CLI }} core config --locale=ja --path={{ WP_HOME }}
    --dbname={{ WP_DB_NAME }} --dbuser={{ WP_DB_USER }}
    --dbpass={{ WP_DB_PASSWORD }} --dbhost={{ WP_DB_HOST }}"
  become: yes

- name: Install wp instance --path={{ WP_HOME }}
  shell: "{{ WP_CLI }} core install --path={{ WP_HOME }}
    --url={{ WP_SERVER_NAME }} --title='{{ WP_TITLE }}' 
    --admin_user={{ WP_ADMIN_USER }} --admin_password={{ WP_ADMINPASS }} 
    --admin_email={{ WP_ADMIN_EMAIL }}"
  become: yes

- name: Put nginx config file
  template:
    src: wordpress.conf
    dest: /etc/nginx/conf.d
  become: yes
  notify: reload nginx
