---
- name: roles/wordpress/tasks/main.yml
  command: echo
- name: Remove wordpress installation
  file:
    path: "{{ WP_HOME }}"
    state: absent
  become: yes
  tags: wp
  when: WP_FORCE_REINSTALL == true
- name: Include core.yml
  include: core.yml
  tags: wp
- name: Include otp.yml
  include: otp.yml
  tags: wp, wp-otp
