---
- name: roles/xdebug/lessmd/main.yml
  command: echo
- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
  become: yes
- name: Install grip
  pip:
    name: grip
  become: yes
- name: Copy lessmd.sh to /etc/profile.d
  copy:
    src: lessmd.sh
    dest: /etc/profile.d
  become: yes
- name: |
    NOTE: Now you can use lessmd command to view a markdown file locally.
  command: echo
