---
- name: roles/xdebug/lessmd/main.yml
  command: echo
- name: Upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
  become: yes
- name: Install grip
  pip:
    name: grip
  become: yes
- name: Check if lessmd exists
  shell: grep lessmd ~/.bashrc >& /dev/null
  register: lessmd
  ignore_errors: yes
- name: Add a function to your {{ ansible_user_dir }}/.bashrc
  patch:
    dest: "{{ ansible_user_dir }}/.bashrc"
    src: bashrc.patch
  when: lessmd.rc != 0
- name: |
    NOTE: Now you can use lessmd command to view a markdown file locally.
  command: echo
