# roles/postgresql/vars/main.yml
PG_VERSION:     9.6
PG_VER_SHORT:   96
PG_BIN_DIR:     /usr/pgsql-{{ PG_VERSION }}/bin
PG_SERVICE:     postgresql-{{PG_VERSION}}
PG_SETUP:       postgresql{{ PG_VER_SHORT }}-setup
PG_DATADIR:     /var/lib/pgsql/{{ PG_VERSION }}/data
PG_INITDB:      "{{ PG_BIN_DIR }}/initdb --locale=ja_JP.UTF-8 --pgdata={{ PG_DATADIR }}"
PG_CONFIG:      "{{ PG_BIN_DIR }}/pg_config"
PG_REPO:        pgdg-centos96-9.6-3.noarch.rpm
PG_REPO_FILE:   pgdg-{{ PG_VER_SHORT }}-centos.repo
