---
- name: roles/mq-server/tasks/main.yml
  command: echo
- name: Install MQ server components
  yum:
    name: "{{ MQ_PACKAGE_BASE_DIR }}/MQServer/{{ item }}{{ MQ_PACKAGE_SUFFIX }}"
    state: present
  with_items:
    - "{{ MQ_SERVER_PACKAGES }}"
  become: yes
- name: Expand file-max
  sysctl:
    name: fs.file-max
    value: 524288
    state: present
  tags: sysctl
  become: yes
