---
- name: roles/mq-php-pecl/tasks/main.yml
  command: echo
- name: yum update. It takes time...
  yum: name=* state=latest
  become: yes
- name: Install dependency
  yum:
    name: "{{ item }}"
  with_items:
    - "{{ PHP_VERSION }}-php-devel"
    - re2c
  become: yes
- name: Get mqseries pecl module
  git:
    clone: yes
    dest: /tmp/pecl-networking-mqseries
    repo: https://github.com/adoy/pecl-networking-mqseries.git
    version: PHP7
    update: no
  ignore_errors: yes
- name: Build module
  shell: export PATH={{ PHP_BIN_DIR }}:$PATH && phpize && ./configure && make
  args:
    chdir: /tmp/pecl-networking-mqseries
- name: Copy module
  copy:
    dest: /opt/remi/php70/root/lib64/php/modules
    remote_src: yes
    src: /tmp/pecl-networking-mqseries/modules/mqseries.so
  become: yes
- name: Copy ini file
  copy:
    dest: /etc/opt/remi/php70/php.d/
    src: 40-mqseries.ini
  become: yes
  notify: restart {{ PHP_FPM }}
