---
- name: start php56-php-fpm
  service: name={{ PHP_FPM }} state=started enabled=yes
  become: yes
- name: restart php56-php-fpm
  service: name={{ PHP_FPM }} state=restarted
  become: yes
- name: start php70-php-fpm
  service: name={{ PHP_FPM }} state=started enabled=yes
  become: yes
- name: restart php70-php-fpm
  service: name={{ PHP_FPM }} state=restarted
  become: yes
