---
- name: roles/mariadb/tasks/main.yml
  command: echo

- name: Install mariadb packages
  yum: name={{item}} state=present
  with_items:
    - mariadb-server
    - mariadb
    - mysql-connector-python
    - MySQL-python
  become: yes

- name: Install mariadb bindings from remi
  yum:
    enablerepo: remi,remi-php72
    name: "{{ PHP_PKG_PREFIX }}-mysqlnd"
  become: yes
  notify: reload php-fpm
  when: PHP_REPO == "remi72"

- name: Install mariadb bindings from webtatic
  yum:
    name: "{{ PHP_PKG_PREFIX }}-mysqlnd"
  become: yes
  notify: reload php-fpm
  when: PHP_REPO == "webtatic72"

- name: Enable mariadb
  service: name=mariadb state=started enabled=yes
  become: yes
