---
- name: roles/mariadb/tasks/main.yml
  command: echo
- name: Install mariadb packages
  yum: name={{item}} state=present
  with_items:
    - mariadb-server
    - mariadb
    - "{{ PHP_PKG_PREFIX }}-mysqlnd"
    - mysql-connector-python
    - MySQL-python
  become: yes
  notify: reload php-fpm
- name: Enable mariadb
  service: name=mariadb state=started enabled=yes
  become: yes
