---
- name: roles/supervisor/tasks/main.yml
  command: echo
- name: Install supervisor
  yum: name={{ item }} state=present
  with_items:
    - supervisor
  become: yes
- name: Settle config file for supervisord
  template:
    src:  laravel-worker.ini
    dest: /etc/supervisord.d/
  become: yes
  notify: restart supervisord
