- name: start php-fpm
  service: name=php-fpm state=started enabled=yes
  become: yes
- name: start php71-php-fpm
  service: name=php71-php-fpm state=started enabled=yes
  become: yes
- name: reload php-fpm
  service: name=php-fpm state=reloaded enabled=yes
  become: yes
- name: reload php71-php-fpm
  service: name=php71-php-fpm state=reloaded enabled=yes
  become: yes
- name: restart php-fpm
  service: name=php-fpm state=restarted enabled=yes
  become: yes
- name: restart php71-php-fpm
  service: name=php71-php-fpm state=restarted enabled=yes
  become: yes
