- name: start php-fpm
  service: name=php-fpm state=started enabled=yes
  become: yes
- name: start php72-php-fpm
  service: name=php72-php-fpm state=started enabled=yes
  become: yes
- name: reload php-fpm
  service: name=php-fpm state=reloaded enabled=yes
  become: yes
- name: reload php72-php-fpm
  service: name=php72-php-fpm state=reloaded enabled=yes
  become: yes
- name: restart php-fpm
  service: name=php-fpm state=restarted enabled=yes
  become: yes
- name: restart php72-php-fpm
  service: name=php72-php-fpm state=restarted enabled=yes
  become: yes
