# Default "composer" RPM package depends on php-5.4, so we install it 
# from the original site.
# Composer will be installed as /usr/bin/composer. It should be at
# /usr/local/bin, ansible does not recognize it unfortunately.
---
- name: roles/composer/tasks/main.yml
  command: echo
- name: get and deploy Composer
  get_url: url=https://getcomposer.org/composer.phar 
    dest=/usr/bin/composer mode=755 force=no
  become: yes
  tags: composer
- name: Prepare $COMPOSER_HOME directory
  file:
    path: "{{ COMPOSER_HOME }}"
    state: directory
- name: Add $COMPOSER_GLOBAL_BIN to $PATH
  template: src=composer.sh dest=/etc/profile.d/
  become: yes

- name: Use https://packagist.jp instead
  composer: 
    command: config
    arguments: -g repos.packagist composer https://packagist.jp
    working_dir: "{{ COMPOSER_HOME }}"
  become: yes
