---
- name: roles/sphinx/tasks/main.yml
  command: echo

- name: Install sphinx
  pip:
    name: sphinx
  become: yes

- name: Install sphinx-autobuild
  pip:
    name: sphinx-autobuild
  become: yes

- name: Install phpdomain
  easy_install:
    name: sphinxcontrib-phpdomain
  become: yes

- name: Install Read the Docs theme for Sphinx
  pip:
    name: sphinx_rtd_theme
  become: yes

