# Dependencies for deleveping PHP Extentsions
---
- name: roles/php-ext/tasks/main.yml
  command: echo
- name: Install packages required for building php extension
  yum: name={{ item }} state=present
  with_items:
    - "{{ PHP_PKG_PREFIX }}-devel"
    - libxml2-devel
    - openssl-devel
    - readline-devel
    - autoconf
    - automake
    - re2c
    - yum-utils
    - rpm-build
    - "{{ PHP_PKG_PREFIX }}-devel"
  become: yes

- name: Enable source package repo for php
  replace:
    path: "{{ PHP_REPO_FILE }}"
    regexp: '^enabled=0$'
    replace: 'enabled=1'
  become: yes
