# Basic Congiguration Control
---
- name: Check if not Ubuntu (not supported)
  command: echo
  failed_when: ansible_lsb.exists is defined
- name: Check if EC2
  stat:
    path: /etc/cloud/cloud.cfg
  register: cloud
# - debug: var=cloud
#   failed_when: true
- include: batch.yml
- include: ec2.yml
  when:
    - cloud.stat.exists == true
    - ansible_distribution == 'CentOS'
    - ansible_distribution_major_version == '7'
- include: dumpall.yml
  tags:
    - dumpall
  when:
    - through | default('false')
