---
- name: roles/base/tasks/mandatory.yml
  command: echo
- name: Install tools required for CentOS 7.x
  yum: name={{item}} state=present
  with_items:
    - chrony
    - glibc-devel
    - gcc-c++
    - python-passlib
    - git
    - elinks
    - patch
    - rsync
    - vim-enhanced
    - nkf
    - bind-utils
    - unzip
    - bzip2
    - wget
    - w3m
    - python2-pip
    - kernel-devel
  become: yes

- name: Prepar directory for WWW_BASE
  file:
    path:     "{{ WWW_BASE }}"
    state:    directory
    owner:    "{{ ansible_user_id }}"
  become: yes
