# Install additional repositories
---
- name: roles/base/tasks/repos.yml
  command: echo

- name: Check for access to the Internet
  wait_for: host=www.yahoo.co.jp port=80 timeout=5

- name: Check existence of RPM-GPG-KEY-EPEL-7
  stat:
    path: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
  register: epel7_key

- name: Import rpm-gpg key for epel
  rpm_key:
    key: http://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
  become: yes
  when: epel7_key.stat.exists == false

- name: Install additional repositories for CentOS 7.x - epel
  yum_repository:
    name: epel-release
    description: Extra Packages for Enterprise Linux 7 - $basearch
    mirrorlist: https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
    failovermethod: priority
    enabled: yes
    gpgkey: file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
    gpgcheck: yes
  become: yes

- name: Import rpm-gpg key for webtatic
  rpm_key:
    key: https://mirror.webtatic.com/yum/RPM-GPG-KEY-webtatic-el7
  become: yes
- name: Install additional repositories for CentOS 7.x - webtatic
  yum:
    name: https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
  become: yes
- name: yum update. It will take a while...
  yum: name=* state=latest
  become: yes
