# Install additional repositories
---
- name: roles/base/tasks/repos.yml
  command: echo
- name: Check for access to the Internet
  wait_for: host=www.yahoo.co.jp port=80 timeout=5
- name: |
    Install additional repositories for CentOS 7.x
    - epel(Enterprise Packages for RedHat Enterprise Linux)
    - remi(Remi's RPM repository)
  yum: name={{item}} state=present
  become: yes
  with_items:
    - epel-release
    - http://rpms.famillecollet.com/enterprise/remi-release-7.rpm
- name: yum update. It takes time...
  yum: name=* state=latest
  become: yes
