---
- name: roles/base/tasks/security.yml
  command: echo

- name: Install tools required for disabling selinux
  yum: 
    name: libselinux-python
    state: present
  become: yes

- name: Disable selinux 
  selinux:
    state: disabled
  become: yes

- name: Disable firewalld
  systemd:
    name: firewalld
    state: stopped
    enabled: no
  become: yes
  when: ansible_distribution_major_version == '7'
  ignore_errors: yes
