---
- name: roles/base/tasks/selinux.yml
  command: echo
- name: Disable selinux 
  selinux: state=disabled
  become: yes
- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  become: yes
