---
- name: roles/base/tasks/selinux.yml
  command: echo
- name: Disable selinux 
  selinux: state=disabled
  become: yes
- name: Check if firewalld exists
  command: systemctl status firewalld
  ignore_errors: yes
  changed_when: false
  register: check_firewalld_service
- name: Disable firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no
  become: yes
  when: check_firewalld_service | succeeded
