---
- name: roles/php/tasks/main.yml
  command: echo

- include_vars: env_{{ PHP_REPO }}.yml

- name: Install PHP dependencies
  yum:
    name: "{{ item }}"
  with_items: "{{ PHP_PACKAGES }}"
  become: yes

# - include: symlink.yml
#   when: PHP_REPO == 'remi71'

- name: php.ini - date.timezone
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;date.timezone ="
    line:         "date.timezone = {{ TIME_ZONE }}"
  become: yes
  when:           PHP_JAPANIZE == true
- name: php.ini - mbstring.language
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;mbstring.language = Japanese"
    line:         "mbstring.language = Japanese"
  become: yes
  when:           PHP_JAPANIZE == true
