---
- name: roles/php/tasks/main.yml
  command: echo
- name: Install PHP stuff from remi repository
  yum: name={{ item }} state=present
  with_items:
    - php70
    - php70-php-mbstring
    - php70-php-xml
    - php70-php-pgsql
  become: yes
- name: make php symlink as an alternative(1)
  file: path=/etc/alternatives/php state=link src=/usr/bin/php70
  become: yes
- name: make php symlink as an alternative(2)
  file: path=/usr/bin/php state=link src=/etc/alternatives/php
  become: yes
- name: Customize php.ini for remi
  patch:
    dest: "{{ PHP_INI_DIR }}/php.ini"
    src:  php.ini.patch
  become: yes
- name: php.ini - date.timezone
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;date.timezone ="
    line:         "date.timezone = {{ TIME_ZONE }}"
  become: yes
  when:           "{{ PHP_JAPANIZE }} == true"
- name: php.ini - mbstring.language
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;mbstring.language = Japanese"
    line:         "mbstring.language = Japanese"
  become: yes
  when:           "{{ PHP_JAPANIZE }} == true"
