---
- name: roles/php/tasks/main.yml
  command: echo
- name: Enable remi-php71 at all times
  shell: sed -i '1,/\[remi-php71-debuginfo\]/ s/enabled=0/enabled=1/' remi-php71.repo
  args:
    chdir: /etc/yum.repos.d
  become: yes
- name: Install PHP stuff from remi repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php-mbstring
    - php-cli
    - php-xml
    - php-pdo
    - php-pgsql
    - php-pecl-zip
  become: yes
- name: add php executables dir to $PATH
  template:
    src:  php.sh
    dest: /etc/profile.d
  become: yes
- name: make patch for php.ini
  template:
    src:  php.ini.patch
    dest: /tmp
- name: Customize php.ini for remi
  patch:
    src:  /tmp/php.ini.patch
    dest: "{{ PHP_INI_DIR }}/php.ini"
    remote_src: yes
  become: yes
- name: php.ini - date.timezone
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;date.timezone ="
    line:         "date.timezone = {{ TIME_ZONE }}"
  become: yes
  when:           "{{ PHP_JAPANIZE }} == true"
- name: php.ini - mbstring.language
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;mbstring.language = Japanese"
    line:         "mbstring.language = Japanese"
  become: yes
  when:           "{{ PHP_JAPANIZE }} == true"
