---
- name: roles/php/tasks/main.yml
  command: echo
- name: Install PHP stuff from remi repository
  yum: name={{ item }} state=present
  with_items:
    - php70
    - php70-php-mbstring
    - php70-php-xml
    - php70-php-fpm
    - php70-php-pgsql
  become: yes
- name: make php symlink as an alternative(1)
  file: path=/etc/alternatives/php state=link src=/usr/bin/php70
  become: yes
- name: make php symlink as an alternative(2)
  file: path=/usr/bin/php state=link src=/etc/alternatives/php
  become: yes
- name: enable php-fpm daemon
  command: echo
  notify: reload php70-php-fpm
- name: put config file /etc/nginx/default.d/php-fpm.conf
  copy: src=php-fpm.conf dest=/etc/nginx/default.d/
  become: yes
  notify: reload nginx
- name: Customize php.ini
  patch:
    dest: "{{ PHP_INI_DIR }}/php.ini"
    src:  php.ini.patch
  when: "{{ JAPANIZE_LARAVEL }} == true"
  become: yes
- name: Customize php-fpm.d/www.conf
  patch:
    dest: "{{ PHP_INI_DIR }}/php-fpm.d/www.conf"
    src:  www.conf.patch
  when: "{{ JAPANIZE_LARAVEL }} == true"
  become: yes
