---
- name: roles/php/tasks/main.yml
  command: echo
- name: Install PHP stuff from remi repository
  yum: name={{ item }} state=present
  with_items:
    - "{{ PHP_VERSION }}"
    - "{{ PHP_VERSION }}-php-mbstring"
    - "{{ PHP_VERSION }}-php-xml"
    - "{{ PHP_VERSION }}-php-pdo"
    - "{{ PHP_VERSION }}-php-pecl-zip"
  become: yes
- name: make php symlink as an alternative(1)
  file: path=/etc/alternatives/php state=link src=/usr/bin/{{ PHP_VERSION }}
  become: yes
- name: make php symlink as an alternative(2)
  file: path=/usr/bin/php state=link src=/etc/alternatives/php
  become: yes
- name: make patch for php.ini
  template:
    src:  php.ini.patch
    dest: /tmp
- name: Customize php.ini for remi
  patch:
    src:  /tmp/php.ini.patch
    dest: "{{ PHP_INI_DIR }}/php.ini"
    remote_src: yes
  become: yes
- name: php.ini - date.timezone
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;date.timezone ="
    line:         "date.timezone = {{ TIME_ZONE }}"
  become: yes
  when:           "{{ PHP_JAPANIZE }} == true"
- name: php.ini - mbstring.language
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;mbstring.language = Japanese"
    line:         "mbstring.language = Japanese"
  become: yes
  when:           "{{ PHP_JAPANIZE }} == true"
