---
- name: roles/php/tasks/main.yml
  command: echo

- name: Install PHP stuff from webtatic repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ PHP_PKG_PREFIX }}-mbstring"
    - "{{ PHP_PKG_PREFIX }}-cli"
    - "{{ PHP_PKG_PREFIX }}-xml"
    - "{{ PHP_PKG_PREFIX }}-pdo"
    - "{{ PHP_PKG_PREFIX }}-pgsql"
    - "{{ PHP_PKG_PREFIX }}-pecl-zip"
  become: yes
- name: php.ini - date.timezone
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;date.timezone ="
    line:         "date.timezone = {{ TIME_ZONE }}"
  become: yes
  when:           PHP_JAPANIZE == true
- name: php.ini - mbstring.language
  lineinfile:
    dest:         "{{ PHP_INI_DIR }}/php.ini"
    regexp:       "^;mbstring.language = Japanese"
    line:         "mbstring.language = Japanese"
  become: yes
  when:           PHP_JAPANIZE == true
