---
- name: roles/php/tasks/symlink.yml
  command: echo

- name: Symlink to {{ PHP_INI_DIR }}/php.ini
  file:
    path: "{{ PHP_INI_DIR }}/php.ini"
    src:  /etc/opt/remi/php71/php.ini
    state: link
  become: yes

- name: Symlink to {{ PHP_INI_DIR }}/php.d
  file:
    path: "{{ PHP_INI_DIR }}/php.d"
    src:  /etc/opt/remi/php71/php.d/
    state: link
  become: yes

- name: Symlink to {{ PHP_LIB_DIR }}
  file:
    path: "{{ PHP_LIB_DIR }}"
    src:  /opt/remi/php71/root/usr/lib64/php/
    state: link
  become: yes

- name: Symlink to {{ PHP_BIN_DIR }}
  file:
    path: "{{ PHP_BIN_DIR }}/{{ item }}"
    src:  /opt/remi/php71/root/usr/bin/{{ item }}
    state: link
  become: yes
  with_items:
    - phar
    - php
    - php-cgi
    - phpize
