---
- name: roles/php-repo/tasks/main.yml
  command: echo

- name: Check if PHP_REPO variable is either 'webtatic71' or 'remi72'
  command: echo
  failed_when:
    - PHP_REPO != 'webtatic71'
    - PHP_REPO != 'remi72'

- name: Inlcude vars specific to webtatic w/ CentOS7
  include_vars:
    file: env_webtatic71.yml
  when: 
    - PHP_REPO == 'webtatic71'
    - _V == '7'

- name: Inlcude vars specific to webtatic w/ CentOS6
  include_vars:
    file: env_webtatic71_cent6.yml
  when: 
    - PHP_REPO == 'webtatic71'
    - _V == '6'

- name: Inlcude vars specific to remi w/ CentOS 6/7
  include_vars:
    file: env_remi.yml
  when: PHP_REPO == 'remi72'

- import_tasks: repos.yml
